services:
  api:
    container_name: api
    build:
      context: ./saleor-api 
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis 
      - jaeger
    volumes:
      - media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - ALLOWED_HOSTS=localhost,api,dashboard
      - JAEGER_AGENT_HOST=jaeger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - saleor-backend-tier

  dashboard:
    container_name: dashboard
    build:
      context: ./saleor-dashboard
      dockerfile: Dockerfile
    ports:
      - 9000:9000
      - 80:80
    depends_on:
      - api
    restart: unless-stopped
    env_file:
      - common.env
      - backend.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - saleor-backend-tier

  db:
    container_name: database 
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "saleor"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - saleor-backend-tier

  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - saleor-backend-tier

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.20.0
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
      - 5775:5775/udp
      - 5778:5778
      - 14268:14268
      - 14250:14250
    volumes:
      - tmpfs:/tmp
    restart: unless-stopped
    networks:
      - saleor-backend-tier

  mailpit:
    container_name: mp 
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
      - 1110:1110
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  media:
  saleor-db:
  data:
  tmpfs:

networks:
  saleor-backend-tier:
    driver: bridge