name: develop branch stuff

on:
  push:
    branches:
      - master
      - develop

jobs:
  developing:
    runs-on: ubuntu-latest
    steps:
        - name: check code
          uses: actions/checkout@v2

        - name: set up python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: installing flake8
          run: pip install flake8
      
        - name: run flake8
          run: flake8 . > flake8_log.log || true

        - name: installing pip-audit
          run: pip install pip-audit

        - name: run pip-audit
          run: pip-audit > pip_audit_report.log || true

        - name: build api docker
          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor:develop .

        - name: health check
          run: |
            docker run -d --name saleor-api ${{ secrets.DOCKER_USERNAME }}/saleor:develop
            docker run -d --name saleor-dashboard ${{ secrets.DOCKER_USERNAME }}/saleor:develop
            curl -f http://localhost:8000/graphql || exit 1
            docker stop saleor-api saleor-dashboard
        
        - name: install trivy
          run: pip install trivy  
        
        - name: trivy scan
          run: trivy image ${{ secrets.DOCKER_USERNAME }}/saleor:develop > trivy_scan_report.log || true

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Push Docker image to Docker Hub
          run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/saleor:develop
