name: production branch stuff

on:
  push:
    branches:
      - production

jobs:
  products:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Ensure Staging Branch is successful
        run: |
          curl -s "https://api.github.com/repos/your-org/your-repo/commits/staging/status" | jq '.statuses[0].state' | grep -q 'success'
      
      - name: build api docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor:production .

      - name: install trivy
        run: pip install trivy  
      
      - name: trivy scan
        run: trivy image ${{ secrets.DOCKER_USERNAME }}/saleor:production > trivy_scan_report.log || true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/saleor:production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Push to AWS
        run: aws ecs update-service --cluster <cluster-name> --service <service-name> --force-new-deployment          