name: staging branch stuff

on:
  push:
    branches:
      - staging

jobs:
  stages:
    runs-on: ubuntu-latest
    steps:
        - name: check code
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: composing validation
          run: |
            docker compose -f docker-compose.yml up -d
            docker compose ps
            docker compose exec api curl -f http://localhost:8000/graphql || echo "something failed"
            docker compose down

        - name: build api docker
          run: |
            cd saleor-api
            docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor:staging .

        - name: Install Trivy
          run: |
            sudo apt-get update && sudo apt-get install -y wget
            wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
            sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

        - name: trivy scan
          run: trivy image ${{ secrets.DOCKER_USERNAME }}/saleor:staging > trivy_scan_report.log || true

        - name: Push Docker image to Docker Hub
          run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/saleor:staging