name: staging branch stuff

on:
  push:
    branches:
      - staging

jobs:
  stages:
    runs-on: ubuntu-latest
    steps:
        - name: check code
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: composing validation
          run: |
            docker compose -f docker-compose.yml up -d
            docker compose ps
            docker compose exec api curl -f http://localhost:8000/graphql || echo "something failed with api"
            docker compose exec dashboard curl -f http://localhost:9000/health || echo "something failed with dashboard"
            docker compose down

        - name: build api docker
          run: |
            cd saleor-api
            docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor:staging .
            cd ..
            cd saleor-dashboard
            docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor:stagingdash .

        - name: Install Trivy
          run: |
            sudo apt-get update && sudo apt-get install -y wget
            wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
            sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

        - name: trivy scan
          run: |
            trivy image ${{ secrets.DOCKER_USERNAME }}/saleor:staging > trivy_scan_report.log || true
            trivy image ${{ secrets.DOCKER_USERNAME }}/saleor:stagingdash > trivy_scandash_report.log || true

        - name: Push Docker image to Docker Hub
          run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/saleor:staging
            docker push ${{ secrets.DOCKER_USERNAME }}/saleor:stagingdash

        - name: Set Commit Status
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                state: 'success',
                context: 'CI/CD Pipeline',
                description: 'Staging checks passed',
                target_url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
              })